### ISSUE TITLE
false-positive: test function names

### ISSUE THREAD

**Issue by ldez** [sivchari/nosnakecase#9]
The `_` is valid inside a test name: it's a basic pattern for non-exposed functions, methods, etc.

```go
func Test_myFunction(t *testing.T) {

}
```

```go
func TestMyStruct_myMethod(t *testing.T) {

}
```

**Comment by gglachant** [comment]
This is also a valid pattern for testable examples.

More information on this is available on the [Testable Examples in Go](https://go.dev/blog/examples) blog post.

**Comment by ldez** [comment]
Yes and also for benchmark and fuzz.

**Comment by sivchari** [comment]
Thanks, I'll fix this problem.
